# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: telegram
type: Opaque
stringData:
  BOT_TOKEN: ENC[AES256_GCM,data:BiPXZoUUa2a15+BlFYFkyiIrQDcp/Is5BA3zSkKpjUrvMxB5SxBcHS2FU0zU,iv:jSxP84ZRqsSS0lC3ZjNbw87LE8TNQBhHo9whOrwNWMA=,tag:lD8Xs31gyBDzDJH4ayOs5Q==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLblJqODZHY0o3Ym9HZit1
        T0dCUTR0NnpwM29HQ3Q3a2N1NkJJNE84c1ZNCjRBZ2k3WkJXY0QyQUFtb0N5L1FS
        RkZSUTMrZmNBcTZhbUJGU0FKM1FvZzAKLS0tIFJUdWlpRHBxM2xYUUVWTmp0bGNW
        czdSL3RKSVM4by9kcFJaalhJdjlYQmMKNuUoc89eUi5pDKTJw/z4QJUye1UvBFPK
        9bcjMeugbfG1ka/03kwPiurXYs0zyrkipfpNor9a4Ep4h6vMqj7/tw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFdURm04aitJ
        emR4akZBa21HdFpYMVB2SkM5ajlSajQxSkp5bHhsYkZRR0x5bEpSZ1VyekVuKzZU
        MFZ4YjBVcUY1OTlXbVFJaWV0NUtQVER1Y0dlbmJqcmVtZVlVdkU2RGR1QjhTYnE4
        d3hPSlkwTXhDcXlNcm9ZRjJYd3JsNEtwR1c3L29zQ3VzM1YxRnVUcGp1enUxYWJH
        clNmRkw0a002bGdlNyswRWRXL2RWd0pjajBKVnNDeGZwN1dFdGswRklSV0pFalhF
        V1I1ZU9jaXB4RGlzS3hDUTB2N1ExM09PeVpxZlpoYk5Pcy9VSG9lb1RvemR3QUZy
        ejY3Z0MyMllMOGJPRzBFbllzZzJJODdQdTJvS3lDZkxKSFJFZzRrdW9oc0ozZ1ZQ
        djFpZW8zSWo1MktxWXZHMWpPaG9CeE1sd0d3Y1dMY3ZnSXdvd1lFZGs0UVRUcDM2
        SUhTQm4wMzZvSGE0Ung2THA2c2l2di83V3VLb0Q0U3ZMR1dvTk52UEptVmc1ZG9J
        SU1TdDIxZU5KcUpGMDdyVnc1bHNZb0lNQlZkMTVRSUFodTFRMGJhaDFERlRUT253
        RFBteHN4ZmptdzQrVGhweTQ4L0N1eUt2aFFDZCtYSzNmbE15b3lzWmcrVStZc0R6
        Njh0am5UcmlDWmJwbG8vaVVDTy84MmM5aGpOUXE0VlZzUlhxRzc4TCtPQjd4QXYx
        VlBJYmhJZjFtUmVIdXdCTDlWU054aTRidW9VeXlrMWlBSW5iZ2EwVVJSRThsTDlv
        WnUyWEpmYi9LREFpZmpseU9CWk4zc0dSeUxjK1Q3anhpMm1IVHpwMnVyTXpRb3hS
        KzhwdXZoVmZpaXk4N2RDR1JEdjBzOVE1aHVKNWtNeWNFaUhLWEljRklvNTg5NkZD
        bkVDNE00N1FZbVhLR1VzZThUbWJuRGZtcEFDYXcyQks3SWxyYStVWkhOOXpuaU41
        Z0lyTnpOV2h6cDdIL0kwb3BJdGNqT3FPRkZnQ2FyZVFZVWVnUDBhWCszRFBwRHNS
        NjVjRzgvZCtWWDA0U1pITW1GQU9rTGVBV2taekRzR0tDZkpycDVGTXlkSDdpTnBC
        RXBuTGxkRksrRnFHcll2ZVI3dGtmbVo5MmR2Y2RRR2xLcWU3TlpGazFHTEN6cmk2
        ZUdEd2loa1dPbHpyMXlDaExxWjN3ejlVWXdTbnFQc3dZN1lQSnZueUlhMk9mSE1v
        N3dpajdEcU1HckFtRW81aTJJa21ENmkvZXpNajA5U1h3M1A4akgvZjBubWlJRzI2
        bVdHeGx6NjY3Nm9BbWdwZS9Vb1UrSU1kaEZBbXdMbjdJdmx6aVU2Ti9TWWFPZWN5
        cmJZcVhkVnFzMEYyOVFpNVprdkRQQWtQamFCZEFnQjB1ZzhtenN2aVdSTFNjL2hT
        ZzdGbStaNGovK0JOSDFBeDFwdHNPalcwdEZaczhxWlNyK2xhTHZyR1RrV05jOXky
        QTZFWFJhWnE3N3JpdW5XRlgyMDBMRHVldXY1OUlubTV5Y2JFY1Zjc1oyZjJ0WWYz
        OGVLdzV0dHBMTzdhRTI2NnlXSDBrdG04N2RuRTZ4Um1nY2VCdmljOFRpWVp0bzZj
        VURtTlduMTFkTjlkTkpkRW1SMUZpc2hZbXY4UWQrRS83MXpvcWtDN3h6bTQvL3dz
        dXVBRDhmS0dzd1Y3UHdvaThSNlBMeEZrT25lV2x4RkZEZGlrcTVsUkdqdU9DQ1lo
        WkpPMEgyc2RrMG4yUnBhbGNQRVc5VUc3LzREU3U0bURZa3dBQjg0UHR2eHluQU5Y
        K0J4QnVObHZPWm5qRktCUU1LdkZ4b0NIRi9oOTNBd25CSGphdzlkeGFyZkdlSWlX
        Rkc4aHdhaW5nVTF1dFIwdGdPbmNaVW1XT09VVGVIa0VBM2t5VUYvRlN4cjFuSWp4
        dmJLZDJhR3hOK3NHd3ZKcXFxRlo0aXMzSVZBeEtiVDdRVENhbFp1ZWtFUDNFUQor
        MVFjeEpmeno5Q2JoWFplaXZHcjJobmVnb1Q4NzEyYW1BR1gvZTlQTlRjCi0tLSA3
        anN1VDdudFVBZndiZURXS0hib3BHNjJZV1REcDVPcmE2OURyeWc2NUFFCozC34jW
        kn8EIqbvPeqJEET5cXU4261Zq1lgxwq9i8MKbIuk5JNR6Fr2EIopQImNfPYftDkq
        UP2xrlRT9rILX5c=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T20:44:49Z"
  mac: ENC[AES256_GCM,data:3DxgzsqPZx1Lt75mqiJogzeq+De6a5iypiAfhfcmumcOBY5neCJ4ZxG5CQIeMJstduZdyRigoZXpHINtzKQD941kQCRNbJsPQOw/SFwokfzRfNV+MUYtADH3uILllXGjKjO+QMxvnMUL/v7iRhqhKoCtf2QYuR5qGqWQXEpEDQw=,iv:LpMrD7dKlQjgsAjxFZ8LISk0bjLrOvi695w8OxwigEc=,tag:2jtM93/O9lLLMPU52uCGrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
