---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium
  namespace: flux-system
spec:
  targetNamespace: kube-system

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  path: ./kubernetes/apps/kube-system/cilium/app
  prune: false # never should be deleted
  wait: true
  interval: 30m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium-config
spec:
  targetNamespace: kube-system

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  path: ./kubernetes/apps/kube-system/cilium/config
  interval: 1h
  prune: true
