---
clusterName: homelab
talosVersion: v1.13.4
kubernetesVersion: v1.34.1
endpoint: https://192.168.30.201:6443
domain: k8s.local
allowSchedulingOnControlPlanes: false
nodes:
  - hostname: nuc-lab-1
    ipAddress: 192.168.30.201
    controlPlane: true
    installDisk: /dev/nvme0n1
  - hostname: pi-controlplane-2
    ipAddress: 192.168.30.202
    controlPlane: true
    installDisk: /dev/nvme0n1
    patches:
      - |-
        machine:
          install:
            wipe: true
  - hostname: pi-worker-1
    ipAddress: 192.168.30.205
    controlPlane: false
    installDisk: /dev/nvme0n1
  - hostname: pi-worker-2
    ipAddress: 192.168.30.206
    controlPlane: false
    installDisk: /dev/nvme0n1
  - hostname: pi-worker-3
    ipAddress: 192.168.30.207
    controlPlane: false
    installDisk: /dev/nvme0n1
controlPlane:
  nodeLabels:
    node.kubernetes.io/exclude-from-external-load-balancers: ""
  nameservers:
    - 1.1.1.1
    - 8.8.8.8

worker:
  nameservers:
    - 1.1.1.1
    - 8.8.8.8

patches:
  - |-
    machine:
      kubelet:
        defaultRuntimeSeccompProfileEnabled: true # Enable container runtime default Seccomp profile.
        disableManifestsDirectory: true # The `disableManifestsDirectory` field configures the kubelet to get static pod manifests from the /etc/kubernetes/manifests directory.
        extraMounts:
          - destination: /var/lib/longhorn
            type: bind
            source: /var/lib/longhorn
            options:
              - bind
              - rshared
              - rw
      features:
        rbac: true # Enable role-based access control (RBAC).
        apidCheckExtKeyUsage: true # Enable checks for extended key usage of client certificates in apid.
      sysctls:
        # Longhorn requires this
        vm.nr_hugepages: "1024"
      kernel:
        modules:
          # longhorn V2 data engine requirements
          - name: nvme_tcp
          - name: vfio_pci
    cluster:
      # Cilium requires this
      network:
        cni:
            name: none
      # disable kube-proxy  - required for Cilium with support for GatewayAPI
      proxy:
        disabled: true
