---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: cilium-chart
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    cgroup:
      automount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    ipam:
      mode: kubernetes
    rollOutCiliumPods: true
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - PERFMON
          - BPF
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
          - PERFMON
          - BPF
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 75m
        memory: 256Mi

    # cilium without kube-proxy
    socketLB:
      enabled: true
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 7445

    # L2 IPAM
    l2announcements:
      enabled: true
      leaseDuration: 10s
      leaseRenewDeadline: 5s
      leaseRetryPeriod: 1s
    l2NeighDiscovery:
      enabled: true
    k8sClientRateLimit: # Client rate limits to prevent flooding the K8s API
      # How to calculate: QPS = N services * (1 / leaseRenewDeadline)
      qps: 5 # default 10
      burst: 10 # default 20
    devices:
      - end0
      - enp1s0

    operator:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      replicas: 2
      minAvailable: 1
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 5m
          memory: 128Mi
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true

    envoy:
      enabled: false
    dashboards:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
        rollOutPods: true
      ui:
        enabled: true
        rollOutPods: true
