---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: o11y
resources:
  - ./ns.yaml
  - ./blackbox-exporter/ks.yaml
  - ./grafana/ks.yaml
  - ./prometheus-adapter/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./smartctl-exporter/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: o11y
    target:
      kind: Namespace
