---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: o11y
resources:
  - ./grafana-operator/ks.yaml
  - ./prometheus-adapter/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./smartctl-exporter/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: o11y
      - op: add
        path: /metadata/labels
        value: {}
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce
        value: privileged
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1enforce-version
        value: latest
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1audit
        value: baseline
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1audit-version
        value: latest
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1warn
        value: baseline
      - op: add
        path: /metadata/labels/pod-security.kubernetes.io~1warn-version
        value: latest
    target:
      kind: Namespace
