---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app longhorn-settings
  namespace: flux-system
spec:
  targetNamespace: longhorn-system

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  path: ./kubernetes/apps/longhorn-system/settings/app
  prune: false # never should be deleted
  wait: false
  interval: 30m
  timeout: 5m
