# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:4DdnZg8ernrs/q8P//8Rja+uCQwewuRUaP2Hdygd1HM=,iv:IX+ocSwmNGKQQRCUH0lyI+LzepsGFm79vQyklClUGHk=,tag:18USV/0iSXjwXXBn2f4uQg==,type:str]
sops:
  age:
    - recipient: age1th0ayw6msyjqrehtp00pp0tj20l70vr4jn7jsuga8katkg69xd7snevqy4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbEw0bEVjUUpnUXhLYmNE
        aDlRVUxEVktuNHkwd0hlMGxKL2JkQUhTTmgwCmpjTWVITDVLV3V2c1pwRGJ4Nmpx
        MitKZnZGeXRvNUxnN0VNVng0c2szTm8KLS0tIDhjL1pKbVBUZWhuNVcxWkhCRUNy
        Y2t6eUgxN3FGK0ZyaUxNTXEvbEZzdDAKMaJ9MhRPhwn6hJpCZ/v/edSSMIBhgUwf
        v3hoCtgMP2e/yRaBeQPVMnrfdEyKAoUj624MafAKUlTsqnV7T28J/w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1pq14eqp74d8cl2de9drsvq99z28hjxxn0hnd3h256s5xjmrtg47j7ee2fg9taqyxfuewu7f6f2p9w7zfls9khc0w7jrfsylaufegu3ukw8ptyqujnmrxjkjyx9hsuzr3vfpyqw29sdj66lh69mdm8fge2q6z0rux3yyw4tama9ljdvv8rdpsmewxj9srz72rf23pk337mdfhe83kjq9tveyvauw3246flyp0qkhzfup42ptqtz9kxyuxc06e40k5y39nw8xwc7w8n2m2ptt865wsjcp3quytejr2ujg4kp9tn34ntq8x3uuqkc0h2dsrvnm9khfvdwdgsaw0y7t5ncs8x6styv7e8fz5pamydajmv2te60hz8385w8syvcttumtmkv56lkteel4z0ptgsyynkav90ez88v3e2dqc4pkkf4xharysxe5nkp9dpvf02j98pryw2d7ajazct39r4zf5gpda35z5edmfjcm7vkq4xv4f8qcj32689ne793rj64qxvcnvnczqkj8g0pwctpj30hvt4g3vadqzr9z54sn04te29439gasxjsj8gggtwuf6mvj3rfkvg33568f9fa3m75purcnr4r83dp2qlcgnzck4qumksyzzjlgdldlc8m2ez7m6v720qjejy9e90r2vdnezgpanjt9hcqy4gf4y74frq5h6pxuv77gnlmpgfsv30t6qqynlwdhv3uk75rtcfmzxxujpx9yvxnvrqycndeq8r7gja2csfjn4f2t2u9exfsqjmwzc70npq2dcsj9l4cfhyd60sde0uqp6em5zuxrmseadnr6sw5jty978jweqvumye9v36mkr5q5fcmqqq5d39azufcxrrmmdv3jsj00tv9pqfvspaz5gyphpmzf9nrcjfc4y3qa04eq9k6nvp8kv2yxtrn5e8x0cg55j73tcy89ntmtv57zufyfcqsgpqrhp8ugvdytq9hew4zj05swm4yugzgvn0rgva3s29z9y5n4grfq3rs60e3q93kuwlx5gdu9stp4v43xslxq0prsql8lsq4fxwzk7g6gg4at83xtqnrq3hq2nqc53yr9z2fm39wunjulcc7yl44q289myjq2guxpvgs0x6vqnfmcnf2zz6332e4e238en2sgy4p60ukpjtwsgf8reg279f6wpyn568lg48fnxsq9xdz45cugn5e492pqfwl3gwmve2lkevyc87vmy7jpfpchs7m5jrx5fprs62nh4mqq8xcucy909dftqzuedcqz6ght2tnwd0ghv7gxy536u562cxfu3u5hvz43gjkj75z6vnthnu669sefkenuyjnp3fgg9fujn8yrhcggjafg02697fzh2md2ghle8uptsjz85qmml3mwpfm22quexczmdpvzu6v3lx45jhms6ur8pcvgts8h5stfg5atjpvh07fhw5uts5c0m3np4nxguskvhlrn0u3l2gqmmqqxtdqtfsv2xmjyft8y0rxwsuyply4ff07vj3x82vuqzhw4jgtgwsewzef6vrgm9ndwgap86wg2k9sdmx2quggsgdz9htkrye53waxgvy5kkreznp0wx8m6kp2wgs63wjj2k6n2pd78v3r3z5vu424ppenq4dcnw9uz54v7s5ck46ze9p4zcfexsysuwky62ztrl2q8y3e3yjrf5h3jhvtw2ckdgvns8wqfcacur3zt08qs29wes26twv42ajltvtcajhyqd94sppvjr2vk6raefh9ur8rrzgg6h5ph92zhd3enshuhsjc6xftsq0qv28ucgls2ksax38u8xur0n33nw729vhuh50p3wtuvck0t0gqal43d3juwj3u5spl9wglfnrldvfl4y80j4wedqnky8dtj2pr3q059cgajld3eg7u9nunnar0lsr0cn2cwxffjvv8wnq4mann69s3auk9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFd3NWdkNG1K
        enAxNUp4bTg5bG5QdHMzOC9Ld0c5SG1OazA0QkxMN2YvdUxwa1FxZEw2SzB1SThp
        dUlnaG91aDBNVklmdkRhdUE2a2JtODFuRGN3ZExVTXZzUkRCZEVmUEtwbUk5MjZN
        RGt3Rk1CSSszampIMkNFbGlXbVg2NE1SNWlOTHVDSVFRS1VadElwd3pxbXlOREg1
        dEhUUzZ3OW0yUTF4bUJNd2ppdnp1NjVici9FTFkyRUtnSlhCS291S2JPMUZRbkpi
        VENob2wzSE5ZSGhJbG5qMWhMOTBTL3h4cXZNbXdVbWxQa3RxMlErZ0VOVUJDT0FS
        Qk1hNUJ2R1FqTmFUdjhja2ZMR3E0aVQvU05nTnBjRThtdnVHcDJocEc1Y0pCeVZv
        ZHJvcm1IU200RFBTQk1Od2RnZDVKLzdsa244QWJReVkxbThWNjc2bTBZM0xEL3hk
        RkpGenV0VlIzUVpTSyttZDNSS0poQitzVjhpT1RxaTVJeldUN042TUdua2ZJVWFn
        Ly9NWUM1cXVFbWVweG80VkJ2QzN2OEdRQ1dYMFU4R1RJYkVjb0pQNUc3bXNwVE01
        MGhFREE3SHMzdDBMY2p3SC9kREZ2ZUtWQmpFN2FjMEhER1prbWZPd043OU01U29C
        ZkxTQWJCNGFwaDBaRlRzVGZIUGpnTXpLM1F0RFZvSk9Ca1hNOS81STRxWkRCOHhs
        UHJFMWl5aFEzMmRGVGtXQXEwdkQ4VExVY2IwVkRhcGM3SERkYkxPZTJyWkhBNVFZ
        bGhaRmpONEt5eFFBRlh5U2JFZ21tQ1NmYkR5YlFreldvT2ZVY0pWVDBqQm10RXVn
        bXNwNlhGQTRpUkpYWERxUkU0ZmFHZ3RQUk94ZjJUODc1T29ySWxOY0RFMThzVndo
        VURYVUdUOUpwL3FMV0h2RUg4NUlPK2lxSEN5aWdpbGhBbkNQSEpLOEFUeWNsRjdp
        ZmZmTGdacW5QM0JvRE1HNm9TOTB5N3dJOXl6R3dHL1JJUWEvMENOTUpHVnJtRXlU
        YWFYWXRkeFgrNkJlOUp1eFF0dW0zVlFMSVlSN2JYc1FUbGl1UHBqZExKR1IrMEMv
        dG9iL0R1WFpSYzduME5mRGdqU1ZOMUZ4NFMreDZuS3FlNlVpTVgwWk1HNkVyOXcv
        Y1FyOEdiRFo3SkZEOTI4WFVEZHVxUXhsc3EwRVhhVG5rZVNnZDlUV3I5MmdZUzNW
        YVR5aVc0K2x0SytLQVJkZlNXTUsvZDdONTlFYUh4MWtlNnBNT25aNUlPN1JRdWZa
        dkpMYTRodmtWSG92MVg2N0xsbllMRVRWd0xIK3pVNDYxb0xXRDI2TTdzc3VKQjFE
        eFlqcTVTTHlwQkw4NGlLbloydmpqNkFhSmlpM3Noc0Fqc1FlY04xVVpJZE5kSUpw
        RnhTMzBoTE9xemM4L0V5TWpGRGhLSDlLc0lZMWwzVXQ3RmhzQnpWMzd1UURFMXFG
        dDh3NHRjazU4ZGUwN2NZNElWRFMrNXk0NFF3YURHa0k1NmpaMnZqaFgvRlRvU2py
        T1NEU2pWaG9hSEpwUVlwU2xJdjU3MkxaVkJPbjVSUjIyMEl4b2M5dkxjb2hVQ3BX
        bytsVHRSeTZnMVJ0Y1dPZlRFcjVkR2NlaVJwRDYxclZKbFNDSTc2anU2bkp6R0lU
        ZDR4cmlWK25seFcxaXV3enFDZkIzRUo1cC8rTHNkNmEveE5oaXZSdytDRWxRenh2
        WEJzWlhYQllpYWlNamF0NTlwbTFheERwY2FHUWVSUHFWa244R1BiSDR3bWlnNHc1
        QnVJMVROYUNEaDVJK0tFWnBQbDFydjJhK0NaTm82ZW9XNGJjR1JLV2xLejlGTEtm
        dEo1TmRLSEFhWnE0Y2VuOWJ4QzB2NXF3aGdhTFg2Z3FIdnBxRjQzRDRjczFKNmVo
        cWo5NWNCREJ3TEQ3V1RyVkZVRVVBYituTjdwcE1FQkhOSVhxK29LSERLbUNhdwpn
        SGdDdURIajc4elVFbGFtd3YvMHB2Sm83cnc3WG0wck1xSnY1eWd4WmZzCi0tLSBS
        SC8zSWZzV1FwM3cvKzNkSW0vd0MvMlZsMVdOR1ErbHp3K1dmdWlWc2NFCoBlkqve
        pT/bmetY7aL5J1Ix1P/koahr5o0U7NygnxfJfuJ8CNhe+OUl9rLEWj3aLM0H+Qh9
        FER/yOQJu+6hd2s=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-25T16:27:30Z"
  mac: ENC[AES256_GCM,data:3TvtgEHUuyxJ2Ksqho2tmb7By1i7WWCalqsazm1aVU68bzjzPR60TqDacow3ynGz0J1wzwzh/ndQtQEkj4SoJ6nduuAiVtlRfYl3G+Y3JUgd5BMEqPsk1Xd4bQuqYhg22+3lxA6WMlzpWIHFyql5RgOFH0NJAF513dz9eTrdAtA=,iv:ZuA71ENpPINn6M+yc5tU0wLv2xOLpjcTwqVn3eo7fYE=,tag:DQJfWbAs7IvaCxLmtnj0QA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
