---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
type: opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQkgybDZzaWZMa1dvTm9m
        RzM1aEdyellQaHA0MGE3OTloQytTcXRzWkdVCkQwbFd3SEpwaGwrVnlLSEJ0Q1dC
        aWMxWWxLY1lDazFiWXFnQnc0bElTeE0KLS0tIHlKckU0MW1aRkUvTTZnc0kxbzdp
        cFk4R2tjUGRmbWNXY0xkbnEwYzFyYzgKI8tW1PTFomrzvpBTNtUUBIDHXSohWhv4
        vb50fkHsW4QVefzQj9noPfcwrDLtzwfbsWU1mbJ3nM2Qk67I0zTVEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1h909jpfpdmnkwnhsmaydx9j9upw34p7r7zjq97d80nw3l7jv8a0qy43up7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-02T10:38:55Z"
  mac: ENC[AES256_GCM,data:0yELoLHTuozHzLjvz7oL00cUtDewJSQUAoUcSaolpZEXotsGYsyeRmejf9UYSMon0bf1QxU7A4Sr8wgpwZvpZ5PhBpzl5n4bnzssP0btlrWxVpIid8H8EG/6Rwln9XmsyTQMoaBVvIcBc3HS/AQ/FpFISYNoJTTUUJRrVsMN67Q=,iv:KpT2Wz0ZpM1ZdghBLP0Z85X8BM4jHXKga+NJ3VEXMw4=,tag:K6D6FkCaK1/+jZ3Uivg61g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
