---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app longhorn
spec:
  targetNamespace: longhorn-system
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 60m
  timeout: 20m
  install:
    crds: CreateReplace
    remediation:
      retries: -1 # infinite retries
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true # Allows deletion of new resources created during the upgrade of the release when it fails.
    remediation:
      strategy: rollback
      retries: 3
  values: # reference: https://github.com/longhorn/charts/tree/v1.12.x/charts/longhorn
    persistence:
      backupTargetName: "" # TODO: fix backups
      defaultClass: true
      dataEngine: v1 # For the default storage class only
      defaultClassReplicaCount: 1
      defaultNodeSelector:
        enable: true
        selector: "worker-storage" # Default storage class only
    global:
      nodeSelector: # Schedules all longhorn components on worker nodes only
        worker-storage: "true"
    defaultSettings:
      v1DataEngine: true
      defaultDataPath: /var/mnt/longhorn
      createDefaultDiskLabeledNodes: true
      # Guaranteed Instance Manager CPU = The estimated max Longhorn volume engine and replica count on a node * 0.1 / The total allocatable CPUs on the node * 100.
      guaranteedInstanceManagerCPU: 12 # default
      storageOverProvisioningPercentage: 100 # default
      storageMinimalAvailablePercentage: 25 # default
      snapshotMaxCount: 20 # Per volume
      replicaSoftAntiAffinity: false
      allowVolumeCreationWithDegradedAvailability: false
      replicaAutoBalance: "least-effort"
      allowEmptyNodeSelectorVolume: false # Disable scheduling of empty node selector volumes to any node.
