---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: cert-manager-chart
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
    replicaCount: 1
    dns01RecursiveNameservers: https://base.dns.mullvad.net/dns-query,https://dns.mullvad.net/dns-query,https://dns.quad9.net/dns-query
    dns01RecursiveNameserversOnly: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    resources: &resources
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        memory: 40Mi
    webhook:
      resources: *resources
    cainjector:
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          memory: 128Mi
