---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/o11y/grafana/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: o11y
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-instance
  namespace: flux-system
spec:
  dependsOn:
    - name: grafana
      namespace: flux-system
    - name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: ./kubernetes/apps/o11y/grafana/instance
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: o11y
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dashboards
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/o11y/grafana/dashboards
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: o11y
  wait: true
  force: true
  patches:
    - patch: |
        - op: add
          path: /spec/instanceSelector
          value:
            matchLabels:
              dashboards: grafana
      target:
        kind: GrafanaDashboard
