apiVersion: ENC[AES256_GCM,data:wa8=,iv:ggZ5YAYEZxU9hFmPA5eNrtEC0GXLXppsI19LFsjdw6s=,tag:I7RZAAgX7vt+YApmU2dH1g==,type:str]
data:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:FkRg2S581pXo/5zMJtbVzLZmYk0rhPDUv1IzVxNsTPylsf8ouCj3Rjd4x2bffuIl/UyEbvaLzx4=,iv:aJFjRu8iZvhI9C6d3c7JqBq5Zkh1gsb0+VKOtsAsJdg=,tag:acOV05RSvZ7R/YHLWTYJyg==,type:str]
kind: ENC[AES256_GCM,data:EgqhoaN/,iv:Z9siP+0RH3IHB3J1O+lzoYmFBaQKIOjdKPih9nJFF7Y=,tag:uoMIkIW8DVBMOVXQxRWm6A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1Y7lep7PYJzcVlbOGjVBj5DSClxAYQ==,iv:mAgOZaFJWrrVjmDFMMsJkXYw7v+TPIOimuGXwbJcDO4=,tag:4cLoo/08dH2lj+1otG5o9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYLzh5aTVxVGFGYkN5M2VO
            QzROcGFhT05SSEVsT3dFNk9ySU11WHMvZEhBCm1vbWJISVdsSGZJRDJDZ3p1Y0ZS
            bGFmemxDM2cvY0g4WjA0eFVTbzdPNHMKLS0tIENQTjY4WTBaNzE2QzdpaW51cjdI
            N2RROVR0ZERFRDVZV1gyK0F4YXBQNEkKuoohHUjtJcPiZ5tKuoIwz+DIItEDlCBy
            Y40+kVLJ/UMA1RByHwexImy+a24/Hn3hM5W3W6pDSoFHhTam+a9csQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h909jpfpdmnkwnhsmaydx9j9upw34p7r7zjq97d80nw3l7jv8a0qy43up7
    lastmodified: "2026-08-31T17:39:43Z"
    mac: ENC[AES256_GCM,data:dhCV0xDrapXMThOK9pX9uYx2YugopZ7g4afr7YdD054MVkzoA+I2VAi1iq8u+6fS/ILjKNP33KIRGvNPnAX8EBRMS35E56w6i0SyUNo8EKVJ6JLfWMeuh3APJ8RhZ6sjvK0WZBrm5KCslLx1GutCY3A8XA0k6quKgh4ss4k4kM4=,iv:sNZzrb9JjKqisXfJL5oFM08s7+iiADfQEP+qYHmgO7A=,tag:SYGVDWdI9w8u8D9MHwnAGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
