apiVersion: v1
data:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:jP00ar2PpgDXfDsdpTQIwWPzf10gNby9DIYRJM33YldBqUtqgC2tdlIIY3+8kZV0Lsv8cIxSQ4o=,iv:Jp93XJZqMv6dbgyN/aFNDpuO2GNfIkPi/L4Dt0VezC0=,tag:yHVLJNx4D+uYNI6Ymc0FWA==,type:str]
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:GDSMLiOp6eI=,iv:oL4ZH4tiMyn5i1Ox9BYfwoKu+GsveXH5EoVFKSeBHnE=,tag:lNY1La70mOBoj+QPdOrwyA==,type:str]
kind: Secret
metadata:
  name: grafana-admin-credentials
type: opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQjNvczV4NGZWSHdzRjA1
        Q0NOYUNnV1lwWlV4c0hNNHJuVzdqaUVqdjJZCndVeVZUei9hWlc0UGttSTVwZnNr
        cXdHeXF1UktkVkl4bWdHTjJwejVtZGMKLS0tIGxJU1dYNnovUko2YVEwZE5LTzlD
        b2pudFd4R0o0ZDMwZlpCcVpqdjd3c28KNQS7J4BxVtfQrnQkqRU8NKHC+boAVTPk
        rCR5ta3Z5IwSKUicZhffCJ3c8PBtqJBn7pt061SfXhb3/XMWPn2SGQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1h909jpfpdmnkwnhsmaydx9j9upw34p7r7zjq97d80nw3l7jv8a0qy43up7
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-02T10:48:10Z"
  mac: ENC[AES256_GCM,data:292d7+6fZGo6o4eyLdRghC4RFK+2fz46OqBXMSZCG3oCQSGuL++rjBw1CSXU1X+4Bs3GhBiVtqnWH6nWDvzaRZ1sLmr6zc5iFm31ordv5Y62koR/t+gM0utbw3Mxgi0YgvVipKv68YoBebS5gtQ/AdiTZTHPnjKOsC9/LsW2R5o=,iv:Na+kAqErGaX9orumGS8P0sa/C4UVEBGZVljNbKiTJmA=,tag:lUca5PPhKubtJ9qZ5M/aYA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
